apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "opensearch-backup.fullname" . }}
  labels:
    {{- include "opensearch-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "opensearch-backup.labels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: snapshotter
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.resources }}
              resources: {{- toYaml .Values.resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              env:
                - name: OPENSEARCH_ENDPOINT
                  value: {{ .Values.opensearch.clusterEndpoint | quote }}
                - name: OPENSEARCH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.opensearch.userSecret }}
                      key: username
                - name: OPENSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.opensearch.userSecret }}
                      key: password
                - name: SNAPSHOT_REPOSITORY
                  value: {{ .Values.snapshotRepository | quote }}
                - name: INDICES
                  value: {{ .Values.indices | quote }}
              command: ['/bin/bash']
              args: ['/scripts/backup.sh']
          volumes:
            - name: scripts
              configMap:
                name: {{ include "opensearch-backup.fullname" . }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          securityContext:
            runAsUser: 65534
