{{- if .Values.velero.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "np.labels" . | nindent 4 }}
  name: default-deny-velero
  namespace: velero
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector: {}
{{- end }}
