{{- if .Values.opensearch.gcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ toYaml .Values.opensearch.gcs.secret }}
type: Opaque
data:
    gcs.client.default.credentials_file: {{ .Values.opensearch.gcs.keyfile | b64enc }}
{{- end }}
