apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-ca
spec:
  ca:
    secretName: opensearch-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-selfsigned
  labels:
spec:
  selfSigned: {}
