{{- if .Values.opensearch.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ toYaml .Values.opensearch.s3.secret }}
type: Opaque
data:
    s3.client.default.access_key: {{ .Values.opensearch.s3.accessKey | b64enc }}
    s3.client.default.secret_key: {{ .Values.opensearch.s3.secretKey | b64enc }}
{{- end }}
