apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensearch-slm.fullname" . }}
  labels:
    {{- include "opensearch-slm.labels" . | nindent 4 }}
data:
  slm-retention.bash: |-
    {{- .Files.Get "scripts/slm-retention.bash" | nindent 4 }}
