---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-manager.fullname" . }}-s3-credentials
  labels:
    {{- include "log-manager.labels" . | nindent 4 }}
stringData:
  s3cfg.ini: |
    host_base         = {{ .Values.s3.regionEndpoint | trimPrefix "https://" | trimPrefix "http://" }}
    {{- if .Values.s3.forcePathStyle }}
    host_bucket       = {{ .Values.s3.regionEndpoint | trimPrefix "https://" | trimPrefix "http://" }}
    {{- else }}
    host_bucket       = %(bucket)s.{{ .Values.s3.regionEndpoint | trimPrefix "https://" | trimPrefix "http://" }}
    {{- end }}
    access_key        = {{ .Values.s3.accessKey }}
    secret_key        = {{ .Values.s3.secretKey }}
    signurl_use_https = True
    use_https         = True
