apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "kubeapi-metrics.fullname" . }}-auth"
  labels:
    {{- include "kubeapi-metrics.labels" . | nindent 4 }}
stringData:
  auth: |
    {{- htpasswd .Values.ingress.username .Values.ingress.password | nindent 4 }}
