{{- if .Values.fluentd.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-fluentd-forwarder-to-opensearch
  namespace: fluentd-system
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: fluentd-forwarder
  egress:
    {{- toYaml .Values.global.scIngressEgress | nindent 4 }}
{{- end }}
