{{- range $user := .Values.opensearch.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $user.secret }}
type: Opaque
data:
    username: {{ $user.username | b64enc }}
    password: {{ $user.password | b64enc }}
    {{ if $user.cookie -}}
    cookie: {{ $user.cookie | b64enc }}
    {{- end}}
{{- end }}
