{{- if .Values.fluentd.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-fluentd-forwarder-user
  namespace: fluentd
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: fluentd-elasticsearch
  ingress:
    - from: {{ toYaml .Values.global.prometheusSelector | nindent 8 }}
      ports:
        - port: 24231
  egress:
    {{- toYaml .Values.global.apiServerEgress | nindent 4 }}
    {{- toYaml .Values.global.dnsServerEgress | nindent 4 }}
    {{- toYaml .Values.global.scIngressEgress | nindent 4 }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: fluentd-system
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: fluentd-aggregator
      ports:
        - port: 24224
{{- end }}
