{{- if .Values.fluentd.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluentd-default-deny-all
  namespace: fluentd
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{ end }}
