{{- $known := lookup "v1" "Service" "default" "kubernetes" }}
{{- $value := lookup "v1" "Secret" .Release.Namespace "alertmanager-alertmanager" }}
{{- if and $known (not $value) (or .Release.IsInstall .Release.IsUpgrade) }}
---
# NOTE: This will always be deleted from the Helm release on the second apply but the secret won't be deleted due to the helm.sh/resource-policy: keep annotation.
# This is to create the initial resource and then hand over the control from the platform administrators to the application developers.
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: alertmanager-alertmanager
data:
{{- ( include "gen.secret" . ) | indent 2 -}}
{{- end }}
