apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos-ingress-secret.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth: |
    {{ .Values.username }}:{{ .Values.passwordHash }}
  username: {{ .Values.username }}
  password: {{ .Values.password }}
