{{- range $namespace, $services := .Values.constraints }}
{{- range $name, $value := $services }}
{{- if hasKey $value.allow "hostNetworkPorts" }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNetworkingPorts
metadata:
  name: {{ printf "host-network-ports-%s-%s" $.Release.Namespace $name | trunc 63 }}
spec:
  match:
    {{- dict "namespace" $namespace "labels" $value.podSelectorLabels | include "podsecuritypolicies.renderMatchInclusion" | nindent 4 }}
  parameters:
    hostNetwork: {{ $value.allow.hostNetworkPorts }}
    min: 1
    max: 65535
{{- end }}
{{- end }}
{{- end }}
