{{- if .Values.fluentd.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-log-manager
  namespace: fluentd-system
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: log-manager
  egress:
    {{- toYaml .Values.global.dnsServerEgress | nindent 4 }}
    {{- toYaml .Values.global.objectStoreEgress | nindent 4 }}
{{- end }}
