{{- $namespaceSelectorLabels := .Values.mutations.namespaceSelectorLabels }}
{{- $namespaces := keys .Values.constraints | sortAlpha }}
{{- $exceptions := .Values.mutations.exceptions }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: {{ printf "supplemental-groups-%s-restricted" .Release.Namespace | trunc 63 }}
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    {{- dict "namespaceSelectorLabels" $namespaceSelectorLabels "namespaces" $namespaces "exceptions" $exceptions | include "podsecuritypolicies.renderMatchExceptions" | nindent 4 }}
  location: "spec.securityContext.supplementalGroups"
  parameters:
    values:
      fromList:
        - 1
    pathTests:
      - subPath: "spec.securityContext.supplementalGroups"
        condition: MustNotExist
