---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "securityadmin.fullname" . }}
  annotations:
    helm.sh/hook: {{ .Values.helm.hook }}
    helm.sh/hook-delete-policy: {{ .Values.helm.deletePolicy }}
    checksum/securityconfig: {{ print .Values.securityConfig | sha256sum }}
  labels:
    {{- include "securityadmin.labels" . | nindent 4 }}
spec:
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "securityadmin.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh
          args:
            - -h
            - "$(OPENSEARCH_HOST)"
            - -p
            - "$(OPENSEARCH_PORT)"
            - -cd
            - /etc/config/security/
            - -icl
            - -nhnv
            - -cacert
            - /etc/cert/admin/ca.crt
            - -cert
            - /etc/cert/admin/tls.crt
            - -key
            - /etc/cert/admin/tls.key
          env:
            - name: OPENSEARCH_HOST
              value: "{{ .Values.opensearch.clusterService }}"
            - name: OPENSEARCH_PORT
              value: "{{ .Values.opensearch.clusterPort }}"
          volumeMounts:
            - name: admin-cert
              mountPath: /etc/cert/admin
            - name: security-config
              mountPath: /etc/config/security
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: admin-cert
          secret:
            secretName: {{ .Values.opensearch.adminCertSecret }}
        - name: security-config
          secret:
            secretName: {{ .Values.opensearch.securityConfigSecret }}
