---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opensearch.securityConfigSecret }}
  annotations:
    helm.sh/hook: {{ .Values.helm.hook }}
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: {{ .Values.helm.deletePolicy }}
  labels:
    {{- include "securityadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.securityConfig | nindent 2 }}
