{{- range $namespace, $services := .Values.constraints }}
{{- range $name, $value := $services }}
{{- if get (default dict $value.mutation) "fsGroup" }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: {{ printf "fsgroup-%s-%s" $.Release.Namespace $name | trunc 63 }}
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    {{- dict "namespace" $namespace "labels" $value.podSelectorLabels | include "podsecuritypolicies.renderMatchInclusion" | nindent 4 }}
  location: "spec.securityContext.fsGroup"
  parameters:
    assign:
      value: {{ $value.mutation.fsGroup }}
    pathTests:
      - subPath: "spec.securityContext.fsGroup"
        condition: MustNotExist
{{- end }}
{{- end }}
{{- end }}
