name: Push Package To GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            with:
              gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
              passphrase: ''
          
          - name: Export PGP Private Key
            run: |
              gpg --export-secret-keys 'Helm Package Signing' > ~/.gnupg/private.gpg

          - name: Helm Registry Login
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, Sign And Push To Registry
            env:
              FOLDERS: 'gatekeeper/constraints, gatekeeper/metrics, gatekeeper/mutations, gatekeeper/podsecuritypolicies, gatekeeper/templates, networkpolicy/common, networkpolicy/generator, networkpolicy/service-cluster, networkpolicy/workload-cluster, opensearch/backup, opensearch/configurer, opensearch/curator, opensearch/secrets, opensearch/securityadmin, opensearch/slm, openstack-monitoring'
            run: |
              ls
              IFS=' ' read -r -a folders <<< "${FOLDERS}"            
              echo "${folders[@]}"
              for folder in "${folders[@]}"; do if [ -d "$folder" ]; then helm package --sign --key 'Helm Package Signing' --keyring ~/.gnupg/private.gpg "$folder" -d "$folder" && helm push "$folder"/*.tgz oci://ghcr.io/${{ github.actor }}; else echo "Folder $folder does not exist. Skipping..."; fi; done
              echo "Done"