name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import PGP Private Key
            run: |
              echo ${{ secrets.PGP_PRIVATE_KEY }} | gpg --import
              echo ${{ secrets.PASSPHRASE }} | gpg --batch --passphrase-fd 0 --export-secret-keys > secret_keys.gpg

          - name: Helm Registry Logi
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, sign, and push Helm charts
            run: |
              folders=($(find . -type d -exec echo {} \;)); for folder in "${folders[@]}"; do if [ -d "$folder" ]; then helm package --sign --key F6F8CA2E185E26E9E74748E3C2A56CF6BDD39E48 --keyring ~/.gnupg/secret_keys.gpg "$folder" -d "$folder" && helm push "$folder"/*.tgz oci://ghcr.io/robinelastisys; else echo "Folder $folder does not exist. Skipping..."; fi; done


