name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            with:
              gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY2 }}
              passphrase: ${{ secrets.PASSPHRASE }}
          
          - name: List keys
            run: | 
              gpg -K
              echo ${{ secrets.PASSPHRASE }} | gpg --export-secret-keys >~/.gnupg/secring.gpg
              gpg --list-keys --keyring ~/.gnupg/secring.gpg

          - name: Helm Registry Logi
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, sign, and push Helm charts
            run: |
              folders=($(find . -type d -exec echo {} \;)); for folder in "${folders[@]}"; do if [ -d "$folder" ]; then helm package --sign --key F4A29E8E41AD41F9DE9CF821AB32EB27336B2CE4 --keyring ~/.gnupg/secring.gpg "$folder" -d "$folder" && helm push "$folder"/*.tgz oci://ghcr.io/robinelastisys; else echo "Folder $folder does not exist. Skipping..."; fi; done


