name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            with:
              gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
              passphrase: ''
          
          - name: Export PGP Private Key
            run: |
              gpg --export-secret-keys 'Helm Package Signing' > ~/.gnupg/private.gpg

          - name: Helm Registry Login
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, Sign And Push To Registry
            env:
              FOLDERS: './opensearch/{curator,securityadmin,secrets,slm,configurer,backup} ./openstack-monitoring/templates ./gatekeeper/{templates,mutations,metrics,constraints,podsecuritypolicies} ./networkpolicy/{generator,common,workload-cluster,service-cluster}'
            run: |
              IFS=' ' read -r -a folders <<< $(echo ${FOLDERS})
              for folder in ${folders[@]}; do
                for dir in $folder; do
                  if [ -d "$dir" ]; then
                    helm package --sign --key 'Helm Package Signing' --keyring ~/.gnupg/private.gpg "$dir" -d "$dir" &&
                    helm push "$dir"/*.tgz oci://ghcr.io/${{ github.actor }}
                  else
                    echo "Folder $dir does not exist. Skipping..."
                  fi
                done
              done
              echo "Done"
