name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            with:
              gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
              passphrase: ''
          
          - name: export PGP Private Key
            run: |
              gpg --export-secret-keys 'helm sign 2' > ~/.gnupg/secret_keys2.gpg

          - name: Helm Registry Logi
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, sign, and push Helm charts
            run: |
              folders=($(find . -type d -exec echo {} \;))

              for folder in "${folders[@]}"; do
                  if [ -d "$folder" ]; then
                      helm package --sign --key 'helm sign 2' --keyring ~/.gnupg/secret_keys2.gpg "$folder" -d "$folder" && helm push "$folder"/*.tgz oci://ghcr.io/robinelastisys

                      # Change directory to the current folder
                      cd "$folder" || continue

                      # Move .prov files to a 'provs' folder
                      mkdir -p provs  # Create 'provs' folder within the current directory if it doesn't exist
                      mv ./*.prov provs/  # Move .prov files to 'provs' folder

                      # Move back to the previous directory (optional)
                      cd - || exit
                  else
                      echo "Folder $folder does not exist. Skipping..."
                  fi
              done
              find . -type f -name "*.prov"