name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            with:
              gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
              passphrase: ''
          
          - name: Export PGP Private Key
            run: |
              gpg --export-secret-keys 'Helm Package Signing' > ~/.gnupg/private.gpg

          - name: Helm Registry Login
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, Sign And Push To Registry
            env:
              FOLDERS: './gatekeeper/{metrics,podsecuritypolicies,mutations,constraints,templates} ./openstack-monitoring/templates ./opensearch/{curator,backup,secrets,securityadmin,slm,configurer} ./networkpolicy/{service-cluster,common,workload-cluster,generator}'   
            run: |
              for folder in "${FOLDERS[@]}"; do if [ -d "$folder" ]; then helm package --sign --key 'Helm Package Signing' --keyring ~/.gnupg/private.gpg "$folder" -d "$folder" && helm push "$folder"/*.tgz oci://ghcr.io/${{ github.actor }}; else echo "Folder $folder does not exist. Skipping..."; fi; done
              echo "Done"