name: Push Package To GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Actions1'
            uses: actions/checkout@main

          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            with:
              gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
              passphrase: ''
          
          - name: Export PGP Private Key
            run: |
              gpg --export-secret-keys 'Helm Package Signing' > ~/.gnupg/private.gpg

          - name: Helm Registry Login
            run: helm registry login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

          - name: Package, Sign And Push To Registry
            env:
              FOLDERS: 'gatekeeper/* networkpolicy/* opensearch/* openstack-monitoring/*'
            run: |
              IFS=' ' read -r -a folders <<< "${FOLDERS}"
              for folder in "${folders[@]}"; do
                for dir in $folder; do
                  for subdir in $(find "$dir" -maxdepth 1 -mindepth 1 -type d); do
                    if [ -d "$subdir" ]; then
                      if [ -f "$subdir/Chart.yaml" ]; then
                        helm package --sign --key 'Helm Package Signing' --keyring ~/.gnupg/private.gpg "$subdir" -d "$subdir" &&
                        helm push "$subdir"/*.tgz oci://ghcr.io/${{ github.actor }}
                      else
                        echo "Chart.yaml file is missing in $subdir. Skipping..."
                      fi
                    else
                      echo "Folder $subdir does not exist. Skipping..."
                    fi
                  done
                done
              done
              echo "Done"