name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Package and push'
            run: |
              helm package .
              echo ${{secrets.GITHUB_TOKEN}} | helm registry login ghcr.io -u elastisys --password-stdin 
              export CHART_VERSION=$(grep 'version:' Chart.yaml | tail -n1 | awk '{ print $2 }')
              export CHART_NAME=$(grep 'name:' Chart.yaml | tail -n1 | awk '{ print $2 }')
              helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/elastisys