name: Push package to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './chart'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Package and push'
            run: |
              helm registry login ghcr.io -u ${{github.actor}} --password ${{secrets.GITHUB_TOKEN}} 
              folders=($(find . -type d -exec echo {} \;)); for folder in "${folders[@]}"; do if [ -d "$folder" ]; then helm package "$folder" && helm push "$folder"*.tgz oci://ghcr.io/${{ github.actor }}; else echo "Folder $folder does not exist. Skipping..."; fi; done
